# Generated by Django 4.1.5 on 2023-01-15 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_rename_post_id_comment_post_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfollowing',
            unique_together={('user', 'following_user')},
        ),
    ]
