# Generated by Django 4.1.5 on 2023-01-15 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_userfollowing_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'post')},
        ),
    ]
